export enum PlayerState {
  BlockingLeft = "BlockingLeft",
  BlockingRight = "BlockingRight",
  DieingLeft = "DieingLeft",
  DieingRight = "DieingRight",
  DuckingLeft = "DuckingLeft",
  DuckingRight = "DuckingRight",
  DuckingBlockingLeft = "DuckingBlockingLeft",
  DuckingBlockingRight = "DuckingBlockingRight",
  DuckingShootingLeft = "DuckingShootingLeft",
  DuckingShootingRight = "DuckingShootingRight",
  GreetingLeft = "GreetingLeft",
  GreetingRight = "GreetingRight",


  StayingLeft = "StayingLeft",
  StayingRight = "StayingRight",
  WalkingLeft = "WalkingLeft",
  WalkingRight = "WalkingRight",
  ShootingLeft = "ShootingLeft",
  ShootingRight = "ShootingRight",
  JumpingLeft = "JumpingLeft",
  JumpingRight = "JumpingRight",
  JumpingBlockingLeft = "JumpingBlockingLeft",
  JumpingBlockingRight = "JumpingBlockingRight",
  JumpingShootingLeft = "JumpingShootingLeft",
  JumpingShootingRight = "JumpingShootingRight",
  HookingLeft = "HookingLeft",
  HookingRight = "HookingRight",
  HookingShootingLeft = "HookingShootingLeft",
  HookingShootingRight = "HookingShootingRight",
  RestingLeft = "RestingLeft",
  RestingRight = "RestingRight",
}
