export enum Position {
  TOP = "TOP",
  LEFT = "LEFT",
  RIGHT = "RIGHT",
  BOTTOM = "BOTTOM",

  TOP_LEFT = "TOP_LEFT",
  TOP_CENTER = "TOP",
  TOP_RIGHT = "TOP_RIGHT",

  CENTER_LEFT = "LEFT",
  CENTER = "CENTER",
  CENTER_RIGHT = "RIGHT",

  BOTTOM_LEFT = "BOTTOM_LEFT",
  BOTTOM_CENTER = "BOTTOM",
  BOTTOM_RIGHT = "BOTTOM_RIGHT"
}
